apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: so9tpprtq-nodejs 
  janus-idp.io/tekton: so9tpprtq-nodejs
  backstage.io/kubernetes-id: so9tpprtq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: so9tpprtq-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  