apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: so9tpprtq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: so9tpprtq-nodejs 
  name: so9tpprtq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: so9tpprtq-nodejs 
